apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
  name: knative-eventing-kafka-broker-tb26b96cf38d47c8a2742db52bf6e5eee
spec:
  componentName: knative-eventing-kafka-broker-test-wathola-forwarder
  application: serverless-operator-release-135
   
  source:
    git:
      url: https://github.com/openshift-knative/eventing-kafka-broker.git
      context: 
      dockerfileUrl: openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
      revision: release-v1.15
