apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  defaultBrokerClass: Kafka
  config:
    config-features:
      kreference-group: "disabled"
      delivery-retryafter: "disabled"
      delivery-timeout: "enabled"
      kreference-mapping: "disabled"
      strict-subscriber: "disabled"
      new-trigger-filters: "disabled"
    config-br-defaults:
      default-br-config: |
        clusterDefault:
          apiVersion: v1
          kind: ConfigMap
          name: kafka-broker-config
          namespace: knative-eventing
